### ISSUE TITLE
Announcement email

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/how_we_work#14]
text here

**Comment by erinmr** [comment]
This email is just a friendly reminder that next Friday (2/26) is the due date for responding to the recent call for participation in Openscapes’ first cohort.  Please see details and next steps below (and an updated presentation attached).

We would like to invite members from your DAAC to upcoming training and leadership opportunities supported through the “Openscapes Framework”, a NASA ROSES Element E2 grant recently awarded to Julia Lowndes, Erin Robinson, and Amanda Tan. 

The project: Openscapes is a highly organized and systematic approach to building skills and community around open, reproducible, and inclusive science (Lowndes et al. 2019). Lowndes, Robinson, and Tan co-designed the Openscapes Framework with NASA as a three year skill-building and community engagement approach for transitioning workflows to the cloud. Opportunities will repeat and iterate each year, empowering researchers to teach and mentor each other while rapidly ramping-up leadership and teaching opportunities for DAAC Trainers so that the Framework continues self-sufficiently in year four. These opportunities begin with identifying and working with folks that are already leading DAAC training efforts to help streamline the way researchers across DAACs learn, create, and share resources. And so –


The opportunity: The first step is to work with 8 Trainers (4 Trainer pairs) across DAACs. Learning together as a cohort in May-July, they will receive Carpentries Instructor training and Openscapes mentorship to help them refine their tutorials and teaching strategies for the cloud. Then in August-November, they will participate with research teams in the Openscapes Champions program to strengthen relationships, identify needs, and test their training. Through these growth opportunities within a broader community engagement approach, they will also gain visibility for their work as well as for their DAACs. The expected time commitment is 3-4 days/month from May-November. This accounts for ~4 hours/month of synchronous calls with the rest of the time being self-directed towards improving training approaches for their specific DAAC.

 
Next steps: In this first year, we are looking for 8 Trainers to participate as pairs from up to 4 DAACs. Please pass this Google Form on to candidates from your DAAC, for them to complete by February 26, 2021. We expect a range of technical ability and training experience; most important at this point is selecting folks that have strong communication and organization skills and have interest in teaching, mentoring, and leadership around data analysis. Please note: we will lead additional cohorts in the next two years, so there will be future opportunities if participation is not possible this year.

**Comment by erinmr** [comment]
Closing issue b/c it's done
